### ISSUE TITLE
Docker issue on Rpi3

### ISSUE THREAD

**Issue by sticklerer** [Dadoum/Provision#36]
I'm using docker with a rpi3 running the latest dietpi.
The Container for Provision is just keep restarting with the following issue in the log:

/opt/anisette_server: error while loading shared libraries: libgphobos.so.3: cannot open shared object file: No such file or directory

I've used the all-in-one command in the README 
Any idea what did i do wrong or what should i do to make it work ?

**Comment by Dadoum** [comment]
Okay, this should be fixed now. Can you retry?

**Comment by Dadoum** [comment]
the docker is not updated yet. so we have to wait a bit

**Comment by sticklerer** [comment]
Seems like it's been updated but the issue is still peresents

**Comment by Dadoum** [comment]
Still not updated, [here is the action](https://github.com/Dadoum/Provision/actions/runs/3633694961/jobs/6130998575) that should finish.

**Comment by sticklerer** [comment]
Sorry , i'm new to github so i was checking docker hub instead in actions . Updated it but same issue

**Comment by Dadoum** [comment]
So now, it should be working.

**Comment by sticklerer** [comment]
It's working now , thanks for the help and the quick fix.
